version: '3.5'
services:
  fuseki:
    image: semapps/jena-fuseki-webacl
    container_name: fuseki_opaline
    networks:
      - semapps
    volumes:
      - ./data/fuseki:/fuseki
      - ./data/staging:/staging
    ports:
      - "3030:3030"
    expose:
      - "3030"
    environment:
      ADMIN_PASSWORD: "admin"

  middleware:
    build: middleware
    container_name: middleware_opaline
    networks:
      - semapps
    depends_on:
      - fuseki
    volumes:
      - ./middleware/:/app
      - ./../semapps:/semapps
      - ./data/fuseki/backups:/app/fuseki-backups # Needed to backup fuseki datasets
    environment:
      - SEMAPPS_SPARQL_ENDPOINT=http://fuseki_opaline:3030/
      - SEMAPPS_MAIN_DATASET=localData
      - SEMAPPS_JENA_USER=admin
      - SEMAPPS_JENA_PASSWORD=admin
      - SEMAPPS_HOME_URL=http://localhost:3000/
      - SEMAPPS_BACKUP_FUSEKI_DATASETS_PATH=/app/fuseki-backups
      - SEMAPPS_OIDC_ISSUER=https://login.lescommuns.org/auth/realms/master/
      - SEMAPPS_OIDC_CLIENT_ID=semapps
      - REPLYTO_EMAIL=${REPLYTO_EMAIL}
      - REPLYTO_LABEL=${REPLYTO_LABEL}
      - MJ_APIKEY_PUBLIC=${MJ_APIKEY_PUBLIC}
      - MJ_APIKEY_PRIVATE=${MJ_APIKEY_PRIVATE}
      # - SEMAPPS_REDIS_CACHE_URL=redis://redis:6379/0
    ports:
      - "3000:3000"
    expose:
      - "3000"
    command: bash -c "yarn install && yarn --cwd ./../semapps/src/middleware run link-all && yarn run link-semapps-packages &&  pm2-runtime 'yarn run dev'"

  backoffice:
    build: backoffice
    container_name: backoffice_opaline
    networks:
      - semapps
    volumes:
      - ./backoffice:/app
      - ./../semapps:/semapps
    environment:
      # - REACT_APP_MIDDLEWARE_URL=http://localhost:3000/
      - REACT_APP_MIDDLEWARE_URL=https://data.moncollectifemploi.fr/
      - REACT_APP_MAPBOX_ACCESS_TOKEN=${REACT_APP_MAPBOX_ACCESS_TOKEN}
      - PORT=5000
    depends_on:
      - middleware
    ports:
      - "5000:5000"
    expose:
      - "5000"
    command: bash -c "yarn install && yarn --cwd ./../semapps/src/frontend run link-all && yarn run link-semapps-packages && yarn run start"

  frontend:
    build: frontend
    container_name: frontend_opaline
    networks:
      - semapps
    volumes:
      - ./frontend:/app
      - ./../semapps:/semapps
    environment:
      - REACT_APP_MIDDLEWARE_URL=http://localhost:3000/
      - REACT_APP_MAPBOX_ACCESS_TOKEN=${REACT_APP_MAPBOX_ACCESS_TOKEN}
      - REACT_APP_CONTACT_EMAIL=${CONTACT_EMAIL}
      - REACT_APP_CONTACT_LABEL=${CONTACT_LABEL}
      - PORT=5001
    depends_on:
      - middleware
    ports:
      - "5001:5001"
    expose:
      - "5001"
    command: bash -c "yarn install && yarn run startwithlink"

  # redis:
  #   image: redis
  #   container_name: redis
  #   expose:
  #     - "6379"
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./data/redis_data:/data
  #   networks:
  #     - semapps
  #   command: ["redis-server", "--appendonly", "yes"]

networks:
  semapps:
    external:
      name: bus_network
